version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.0.1

jobs:
 herokuDeploy:
  executor: heroku/default
  environment:
   HEROKU_APP_NAME: "recognitionn"
  steps:
    - checkout
    - heroku/install
    - run:
       command: |
        heroku 
    - heroku/deploy-via-git

workflows:
  main:
    jobs:
      - herokuDeploy
