version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.0.1

jobs:
 herokuDeploy:
  executor: python/default
  environment:
   HEROKU_APP_NAME: "recognitionn"
  steps:
    - python/load-cache
    - checkout
    - heroku/install
    - heroku/deploy-via-git
    - python/save-cache

workflows:
  main:
    jobs:
      - herokuDeploy
